services:
  dev:
    container_name: itau-java-dev
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./:/app/"
  
  prod:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8081:8080"